### ISSUE TITLE
Label / textarea niet gekoppeld

### ISSUE THREAD

**Issue by KrijnHoetmer** [Sascha-davidson/all-human-accessible-website#1]
Probeer hetzelfde patroon als bij je inputs te gebruiken; nesten (of met `for`/`id` attributen).

https://github.com/Sascha-davidson/all-human-accessible-website/blob/bf5465a7219c56cfb85b09eacef8d1b20a3e58b0/index.html#L201

**Comment by Sascha-Davidson** [comment]
ik heb dit verbeterd inclusief op alle pagina's

https://github.com/Sascha-davidson/all-human-accessible-website/blob/main/index.html#L262

**Comment by KrijnHoetmer** [comment]
Lijkt in wat je linkt nog niet opgelost, toch?
