### ISSUE TITLE
Dubbele markers in Safari

### ISSUE THREAD

**Issue by KrijnHoetmer** [Sascha-davidson/all-human-accessible-website#4]
Leuk bugje in Safari :)

<img width="497" alt="image" src="https://user-images.githubusercontent.com/685870/205264508-1dd4cb32-c424-42d7-9b42-3dc9c3d24520.png">

**Comment by Sascha-Davidson** [comment]
ik heb mijn marker uit gezet omdat ik een eigen marker toevoeg

@tom-2810 heeft gezegd hoe je een marker kan bewerken. (zie hieronder)

https://github.com/Sascha-davidson/all-human-accessible-website/blob/main/styles/styles.css#L1327-L1329
